// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4aanb4l-BScpvPKorN3BHkeZlktOdMl8',
    appId: '1:857982385583:web:7f89bee49a872c911f035a',
    messagingSenderId: '857982385583',
    projectId: 'a-aprender-a-programar-flutter',
    authDomain: 'a-aprender-a-programar-flutter.firebaseapp.com',
    storageBucket: 'a-aprender-a-programar-flutter.appspot.com',
    measurementId: 'G-MDDV7YSJK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTLmxbalvS4yKJeMmgaKndWEt4bdbFo5A',
    appId: '1:857982385583:android:19287d629517171e1f035a',
    messagingSenderId: '857982385583',
    projectId: 'a-aprender-a-programar-flutter',
    storageBucket: 'a-aprender-a-programar-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbajxlqbicwOp7mhJzayvQ0DKOu4A54Ew',
    appId: '1:857982385583:ios:ee9299b69e664d321f035a',
    messagingSenderId: '857982385583',
    projectId: 'a-aprender-a-programar-flutter',
    storageBucket: 'a-aprender-a-programar-flutter.appspot.com',
    iosClientId: '857982385583-mqea2o407mdv01lgk7pft95kj2l68ktm.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbajxlqbicwOp7mhJzayvQ0DKOu4A54Ew',
    appId: '1:857982385583:ios:117325e57d6cfc2f1f035a',
    messagingSenderId: '857982385583',
    projectId: 'a-aprender-a-programar-flutter',
    storageBucket: 'a-aprender-a-programar-flutter.appspot.com',
    iosClientId: '857982385583-lgm3tkgpmsbbfdtd0q3ejp9nej3md796.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart.RunnerTests',
  );
}
